---
kind: pipeline
type: docker
name: x86

platform:
  arch: amd64

steps:
- name: build
  image: plugins/docker
  settings:
    repo: blafy/caddockery
    tags: latest-amd64
    username: blafy
    password:
        from_secret: dockerpwd

---
kind: pipeline
type: docker
name: arm8

platform:
  arch: arm64

steps:
- name: build
  image: plugins/docker
  settings:
    repo: blafy/caddockery
    tags: latest-arm64
    username: blafy
    password:
        from_secret: dockerpwd
        
---
kind: pipeline
type: docker
name: manifest

platform:
  arch: arm64

steps:
- name: manifest
  image: plugins/docker
  settings:
    username: blafy
    password:
        from_secret: dockerpwd
  commands:
  - docker manifest create blafy/caddockery:latest blafy/caddockery:latest-arm64 blafy/caddockery:latest-amd64
  - docker manifest push blafy/caddockery:latest
  
depends_on:
- x86
- arm8
