---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    repo: blafy/caddockery
    auto_tag: true
    username: blafy
    password:
        from_secret: dockerpwd
